[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stream-parse-openttd"
version = "0.0.0.dev0"

[tool.hatch.build]
include = [
  "stream_parse_openttd.py"
]
